Question.create text: "What group of learned men did Aerys II, The Mad King, favor?", question_type: "alcolyte"
Choice.create question_id: 1, text: "The Pyromancers", correct: "true"
Choice.create question_id: 1, text: "The Maesters"
Choice.create question_id: 1, text: "The Kingswood Brotherhood"
Choice.create question_id: 1, text: "The Silent Sisters"

Question.create text: "What was the name of the Valyrian Steel sword wielded by Aegon The Conqueror?", question_type: "alcolyte"
Choice.create question_id: 2, text: "'Blackfyre'", correct: "true"
Choice.create question_id: 2, text: "'Dark Sister'"
Choice.create question_id: 2, text: "'Dawn'"
Choice.create question_id: 2, text: "'Ice'"

Question.create text: "Who was the King That Knelt?", question_type: "alcolyte"
Choice.create question_id: 3, text: "Torrhen Stark", correct: "true"
Choice.create question_id: 3, text: "The Storm King"
Choice.create question_id: 3, text: "Mern"
Choice.create question_id: 3, text: "The Titan's Bastard"

Question.create text: "Where is the home of the Faceless Men?", question_type: "alcolyte"
Choice.create question_id: 4, text: "Braavos", correct: "true"
Choice.create question_id: 4, text: "Norvos"
Choice.create question_id: 4, text: "Dorne"
Choice.create question_id: 4, text: "Yunkai"

Question.create text: "Which of the following is not a Sworn House to the Starks?", question_type: "alcolyte"
Choice.create question_id: 5, text: "Cerwyn"
Choice.create question_id: 5, text: "Umber"
Choice.create question_id: 5, text: "Hornwood"
Choice.create question_id: 5, text: "Arryn", correct: "true"

Question.create text: "How many Gods does the lady Catelyn pray to?", question_type: "alcolyte"
Choice.create question_id: 6, text: "1"
Choice.create question_id: 6, text: "6"
Choice.create question_id: 6, text: "3"
Choice.create question_id: 6, text: "7", correct: "true"

Question.create text: "What is the family symbol of House Targaryen?", question_type: "alcolyte"
Choice.create question_id: 7, text: "Turtle"
Choice.create question_id: 7, text: "Wolf"
Choice.create question_id: 7, text: "Dragon", correct: "true"
Choice.create question_id: 7, text: "Firefly"

Question.create text: "Who is the youngest son of Eddard Stark?", question_type: "alcolyte"
Choice.create question_id: 8, text: "Jon Snow"
Choice.create question_id: 8, text: "Robb"
Choice.create question_id: 8, text: "Bran"
Choice.create question_id: 8, text: "Rickon", correct: "true"

Question.create text: "Who was the most beloved of the Targaryen kings by the smallfolk?", question_type: "alcolyte"
Choice.create question_id: 9, text: "Aegon The Conqueror"
Choice.create question_id: 9, text: "Jahaerys The Conciliator"
Choice.create question_id: 9, text: "Baelor The Blessed", correct: "true"
Choice.create question_id: 9, text: "Daeron II"

Question.create text: "What is the richest House in Westeros?", question_type: "alcolyte"
Choice.create question_id: 10, text: "Lannister", correct: "true"
Choice.create question_id: 10, text: "Stark"
Choice.create question_id: 10, text: "Tyrell"
Choice.create question_id: 10, text: "Greyjoy"

Question.create text: "How did Robert Baratheon kill Rhaegar Targaryen?", question_type: "maester"
Choice.create question_id: 11, text: "caved his head in with a blow from his hammer"
Choice.create question_id: 11, text: "caved his chest in with a blow from his hammer", correct: "true"
Choice.create question_id: 11, text: "stabbed him in the eye with a spear"
Choice.create question_id: 11, text: "crossbow bolt in the groin"

Question.create text: "What is the name of Ser Jorah's second wife?", question_type: "maester"
Choice.create question_id: 12, text: "Lyanna"
Choice.create question_id: 12, text: "Lynesse", correct: "true"
Choice.create question_id: 12, text: "Daisy"
Choice.create question_id: 12, text: "Lollies"

Question.create text: "What is the name of the singer blamed for killing Lysa Arryn?", question_type: "maester"
Choice.create question_id: 13, text: "Lanster"
Choice.create question_id: 13, text: "Marillion", correct: "true"
Choice.create question_id: 13, text: "Tyrek"
Choice.create question_id: 13, text: "Erik"

Question.create text: "What is the sigil of Petyr Baelish's grandfather?", question_type: "maester"
Choice.create question_id: 14, text: "titan's head", correct: "true"
Choice.create question_id: 14, text: "robin"
Choice.create question_id: 14, text: "sparrow"
Choice.create question_id: 14, text: "crossed bastard swords under a crescent moon"

Question.create text: "What poison was used to kill Jon Arryn?", question_type: "maester"
Choice.create question_id: 15, text: "spider's nectar"
Choice.create question_id: 15, text: "tears of Lys", correct: "true"
Choice.create question_id: 15, text: "dragon's blood"
Choice.create question_id: 15, text: "aether potion"

Question.create text: "Where was Varys born?", question_type: "maester"
Choice.create question_id: 16, text: "Lys", correct: "true"
Choice.create question_id: 16, text: "King's Landing"
Choice.create question_id: 16, text: "Sunspear"
Choice.create question_id: 16, text: "Pentos"

Question.create text: "Which of the seven kingdoms was brought under Targaryen rule through a dual marriage pact?", question_type: "maester"
Choice.create question_id: 17, text: "Dorne", correct: "true"
Choice.create question_id: 17, text: "The Westerlands"
Choice.create question_id: 17, text: "The Reach"
Choice.create question_id: 17, text: "The Vale"

Question.create text: "Who forged King Roberts war hammer?", question_type: "maester"
Choice.create question_id: 18, text: "Gendry"
Choice.create question_id: 18, text: "Donal Noye", correct: "true"
Choice.create question_id: 18, text: "Tobho Mott"
Choice.create question_id: 18, text: "Tycho Nestoris"

Question.create text: "Who killed Jon Arryn", question_type: "maester"
Choice.create question_id: 19, text: "Eddard Stark"
Choice.create question_id: 19, text: "Lysa Arryn", correct: "true"
Choice.create question_id: 19, text: "Robin Arryn"
Choice.create question_id: 19, text: "Tyrion Lannister"

Question.create text: "Who was the closest common ancestor of Daenarys Stormborn Targaryen and Robert Baratheon?", question_type: "maester"
Choice.create question_id: 20, text: "Aegon V, \"The Unlikely\"", correct: "true"
Choice.create question_id: 20, text: "Daemon Blackfyre"
Choice.create question_id: 20, text: "Rhaenarys Targaryen"
Choice.create question_id: 20, text: "Aegon The Conqueror"

Question.create text: "\"Spotted Sylva,\" one of Arrianne Martell's dearest friends, is knick-named as such because of her freckles and also because she is the heir to Spottswood. What is her real name?", question_type: "archmaester"
Choice.create question_id: 21, text: "Sylva Santagar", correct: "true"
Choice.create question_id: 21, text: "Sylva Spottswood"
Choice.create question_id: 21, text: "Sylva Dane"
Choice.create question_id: 21, text: "Sylva Royce"
Choice.create question_id: 21, text: "Sylva Estermont"
Choice.create question_id: 21, text: "Sylva Martel"
Choice.create question_id: 21, text: "Sylva Sand"
Choice.create question_id: 21, text: "Sylva Yronwood"

Question.create text: "As of \"A Dance with Dragons,\" what is the current location of Jorah Mormont's second wife?", question_type: "archmaester"
Choice.create question_id: 22, text: "She rests in a watery grave at the bottom of the sunset sea."
Choice.create question_id: 22, text: "Pentos"
Choice.create question_id: 22, text: "Lys", correct: "true"
Choice.create question_id: 22, text: "Norvos"
Choice.create question_id: 22, text: "Braavos"
Choice.create question_id: 22, text: "Myr"
Choice.create question_id: 22, text: "Volantis"
Choice.create question_id: 22, text: "Tyrosh"

Question.create text: "As of the close of A Dance with Dragons, which great-grandson of Walder Frey is the heir to The Twins?", question_type: "archmaester"
Choice.create question_id: 23, text: "Red Ronnet Frey"
Choice.create question_id: 23, text: "Ryman Frey"
Choice.create question_id: 23, text: "Stevron Frey"
Choice.create question_id: 23, text: "Black Walder Frey"
Choice.create question_id: 23, text: "Edwin Frey", correct: "true"
Choice.create question_id: 23, text: "Petyr Frey"
Choice.create question_id: 23, text: "Aegon Frey"

Question.create text: "In the days following Eddard Stark's execution, Sansa spends her time sleeping, sobbing, and sleeping again. Where was her room located during this time of mourning?", question_type: "archmaester"
Choice.create question_id: 24, text: "Maegor’s Holdfast", correct: "true"
Choice.create question_id: 24, text: "Tower of the Hand"
Choice.create question_id: 24, text: "Maidenvault"
Choice.create question_id: 24, text: "the royal sept"
Choice.create question_id: 24, text: "White Sword Tower"
Choice.create question_id: 24, text: "The dungeon of the Red Keep"
Choice.create question_id: 24, text: "The Godswood at the Red Keep"
Choice.create question_id: 24, text: "In the wynds of Flea Bottom"

Question.create text: "What is the full name given by Bronn to the bastard son of his newly wed wife Lollys Stokeworth?", question_type: "archmaester"
Choice.create question_id: 25, text: "Tyrion Stokeworth"
Choice.create question_id: 25, text: "Tyrion Steelshanks"
Choice.create question_id: 25, text: "Tywin Stokeworth"
Choice.create question_id: 25, text: "Tywin Tanner"
Choice.create question_id: 25, text: "Tyrion Baker"
Choice.create question_id: 25, text: "Hot Pie"
Choice.create question_id: 25, text: "Tyrek Smith"
Choice.create question_id: 25, text: "Tyrion Tanner", correct: "true"

Question.create text: "When Quentyn Martell was dispatched by Prince Doran to meet with Danerys Targaryen in the Free Cities he took Maester Kedry with him in his company. Why did Quentyn and Maester Kedry part company?", question_type: "archmaester"
Choice.create question_id: 26, text: "Maester Kedry became ill with the flux during the voyage and died."
Choice.create question_id: 26, text: "Maester Kedry died at the hands of thieves in Volantis."
Choice.create question_id: 26, text: "Maester Kedry was killed after their ship was attacked by corsairs during the voyage.", correct: "true"
Choice.create question_id: 26, text: "Maester Kendry was poisoned by a nameless assassin."
Choice.create question_id: 26, text: "Maester Kedry caught greyscale and Gerris Drinkwater killed him as a lost cause."
Choice.create question_id: 26, text: "Maester Kedry returned to Sunspear after it was discovered that Danaerys was lingering in Mereen."
Choice.create question_id: 26, text: "Maester Kendry became ill during the voyage and was left in the care of a young Dornish knight in Volantis where he awaits Quentyn's return."
Choice.create question_id: 26, text: "Maester Kendry threw away his maester's chain and took up with a harlot."

Question.create text: "Which Targaryen was not know for his bookish proclivities?", question_type: "archmaester"
Choice.create question_id: 27, text: "Rhaegar Targaryen"
Choice.create question_id: 27, text: "Aerys I Targaryen"
Choice.create question_id: 27, text: "Daeron II Targaryen"
Choice.create question_id: 27, text: "Daeron I Targeryen", correct: "true"
Choice.create question_id: 27, text: "Baelor I Targaryen"

Question.create text: "Which of the following is not an alias of Lord Leyton Hightower?", question_type: "archmaester"
Choice.create question_id: 28, text: "the Old Man of Oldtown"
Choice.create question_id: 28, text: "the Voice of Oldtown"
Choice.create question_id: 28, text: "Lord of the Port"
Choice.create question_id: 28, text: "Lord of the Hightower"
Choice.create question_id: 28, text: "Defender of the Citadel"
Choice.create question_id: 28, text: "Beacon of the South"
Choice.create question_id: 28, text: "Guardian of the Flame", correct: "true"
Choice.create question_id: 28, text: "Champion of the Shield Islands"

Question.create text: "Which character uttered this famous line: \"Rhaegar fought valiantly, Rhaegar fought nobly, Rhaegar fought honorably. And Rhaegar died.\" ", question_type: "archmaester"
Choice.create question_id: 29, text: "Barristan Selmy"
Choice.create question_id: 29, text: "Eddard Stark"
Choice.create question_id: 29, text: "Tywin Lannister"
Choice.create question_id: 29, text: "Jorah Mormont", correct: "true"
Choice.create question_id: 29, text: "Jeor Mormont"
Choice.create question_id: 29, text: "Viserys Targaryen"
Choice.create question_id: 29, text: "Varys"
Choice.create question_id: 29, text: "Illirio Mopatis"

Question.create text: "Who was the father of Aegon \"The Conqueror\"?", question_type: "archmaester"
Choice.create question_id: 30, text: "it is unknown"
Choice.create question_id: 30, text: "Aerion Targaryen", correct: "true"
Choice.create question_id: 30, text: "Orys Targaryen"
Choice.create question_id: 30, text: "Aemon Targaryen"
Choice.create question_id: 30, text: "Daemon Targaryen"
Choice.create question_id: 30, text: "Aerys Targaryen"
Choice.create question_id: 30, text: "Viserys Targaryen"
Choice.create question_id: 30, text: "Jon Targaryen"

